[tool.poetry]
name = "no-project-sockets"
version = "0.1.0"
description = ""
authors = ["Sergey Mironov <ka6ah505@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
